"""Fernet symmetric encryption for database credentials at rest."""

from __future__ import annotations

from cryptography.fernet import Fernet, InvalidToken

__all__ = ["EncryptionService", "InvalidToken"]


class EncryptionService:
    """Encrypt/decrypt database passwords using Fernet (AES-128-CBC + HMAC-SHA256).

    Key must be a URL-safe base64-encoded 32-byte key (generated by Fernet.generate_key()).
    """

    def __init__(self, key: str) -> None:
        self._fernet = Fernet(key.encode() if isinstance(key, str) else key)

    def encrypt(self, plaintext: str) -> str:
        """Encrypt a plaintext password. Returns URL-safe base64 ciphertext."""
        return self._fernet.encrypt(plaintext.encode()).decode()

    def decrypt(self, ciphertext: str) -> str:
        """Decrypt a ciphertext back to plaintext password."""
        return self._fernet.decrypt(ciphertext.encode()).decode()

    @staticmethod
    def generate_key() -> str:
        """Generate a new Fernet key suitable for RECVIZ_ENCRYPTION_KEY."""
        return Fernet.generate_key().decode()
