/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppExplorerIndexRouteImport } from './routes/_app/explorer/index'
import { Route as AppDatasetsIndexRouteImport } from './routes/_app/datasets/index'
import { Route as AppDashboardsIndexRouteImport } from './routes/_app/dashboards/index'
import { Route as EmbedDashboardsDashboardIdRouteImport } from './routes/embed/dashboards/$dashboardId'
import { Route as AppDatasetsNewRouteImport } from './routes/_app/datasets/new'
import { Route as AppDashboardsDashboardIdRouteImport } from './routes/_app/dashboards/$dashboardId'
import { Route as AppDatasetsDatasetIdEditRouteImport } from './routes/_app/datasets/$datasetId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerIndexRoute = AppExplorerIndexRouteImport.update({
  id: '/explorer/',
  path: '/explorer/',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsIndexRoute = AppDatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsIndexRoute = AppDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AppRoute,
} as any)
const EmbedDashboardsDashboardIdRoute =
  EmbedDashboardsDashboardIdRouteImport.update({
    id: '/embed/dashboards/$dashboardId',
    path: '/embed/dashboards/$dashboardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppDatasetsNewRoute = AppDatasetsNewRouteImport.update({
  id: '/datasets/new',
  path: '/datasets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsDashboardIdRoute =
  AppDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => AppRoute,
  } as any)
const AppDatasetsDatasetIdEditRoute =
  AppDatasetsDatasetIdEditRouteImport.update({
    id: '/datasets/$datasetId/edit',
    path: '/datasets/$datasetId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards/$dashboardId': typeof AppDashboardsDashboardIdRoute
  '/datasets/new': typeof AppDatasetsNewRoute
  '/embed/dashboards/$dashboardId': typeof EmbedDashboardsDashboardIdRoute
  '/dashboards/': typeof AppDashboardsIndexRoute
  '/datasets/': typeof AppDatasetsIndexRoute
  '/explorer/': typeof AppExplorerIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/datasets/$datasetId/edit': typeof AppDatasetsDatasetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards/$dashboardId': typeof AppDashboardsDashboardIdRoute
  '/datasets/new': typeof AppDatasetsNewRoute
  '/embed/dashboards/$dashboardId': typeof EmbedDashboardsDashboardIdRoute
  '/dashboards': typeof AppDashboardsIndexRoute
  '/datasets': typeof AppDatasetsIndexRoute
  '/explorer': typeof AppExplorerIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/datasets/$datasetId/edit': typeof AppDatasetsDatasetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboards/$dashboardId': typeof AppDashboardsDashboardIdRoute
  '/_app/datasets/new': typeof AppDatasetsNewRoute
  '/embed/dashboards/$dashboardId': typeof EmbedDashboardsDashboardIdRoute
  '/_app/dashboards/': typeof AppDashboardsIndexRoute
  '/_app/datasets/': typeof AppDatasetsIndexRoute
  '/_app/explorer/': typeof AppExplorerIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/datasets/$datasetId/edit': typeof AppDatasetsDatasetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards/$dashboardId'
    | '/datasets/new'
    | '/embed/dashboards/$dashboardId'
    | '/dashboards/'
    | '/datasets/'
    | '/explorer/'
    | '/reports/'
    | '/settings/'
    | '/datasets/$datasetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards/$dashboardId'
    | '/datasets/new'
    | '/embed/dashboards/$dashboardId'
    | '/dashboards'
    | '/datasets'
    | '/explorer'
    | '/reports'
    | '/settings'
    | '/datasets/$datasetId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboards/$dashboardId'
    | '/_app/datasets/new'
    | '/embed/dashboards/$dashboardId'
    | '/_app/dashboards/'
    | '/_app/datasets/'
    | '/_app/explorer/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/datasets/$datasetId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EmbedDashboardsDashboardIdRoute: typeof EmbedDashboardsDashboardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer/': {
      id: '/_app/explorer/'
      path: '/explorer'
      fullPath: '/explorer/'
      preLoaderRoute: typeof AppExplorerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasets/': {
      id: '/_app/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AppDatasetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/embed/dashboards/$dashboardId': {
      id: '/embed/dashboards/$dashboardId'
      path: '/embed/dashboards/$dashboardId'
      fullPath: '/embed/dashboards/$dashboardId'
      preLoaderRoute: typeof EmbedDashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/datasets/new': {
      id: '/_app/datasets/new'
      path: '/datasets/new'
      fullPath: '/datasets/new'
      preLoaderRoute: typeof AppDatasetsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/$dashboardId': {
      id: '/_app/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof AppDashboardsDashboardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasets/$datasetId/edit': {
      id: '/_app/datasets/$datasetId/edit'
      path: '/datasets/$datasetId/edit'
      fullPath: '/datasets/$datasetId/edit'
      preLoaderRoute: typeof AppDatasetsDatasetIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardsDashboardIdRoute: typeof AppDashboardsDashboardIdRoute
  AppDatasetsNewRoute: typeof AppDatasetsNewRoute
  AppDashboardsIndexRoute: typeof AppDashboardsIndexRoute
  AppDatasetsIndexRoute: typeof AppDatasetsIndexRoute
  AppExplorerIndexRoute: typeof AppExplorerIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppDatasetsDatasetIdEditRoute: typeof AppDatasetsDatasetIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardsDashboardIdRoute: AppDashboardsDashboardIdRoute,
  AppDatasetsNewRoute: AppDatasetsNewRoute,
  AppDashboardsIndexRoute: AppDashboardsIndexRoute,
  AppDatasetsIndexRoute: AppDatasetsIndexRoute,
  AppExplorerIndexRoute: AppExplorerIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppDatasetsDatasetIdEditRoute: AppDatasetsDatasetIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EmbedDashboardsDashboardIdRoute: EmbedDashboardsDashboardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
